CONFIG_PORT: 8888
EUREKA_PORT: 8001
GATEWAY_PORT: 8000

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/dopimex_${spring.application.name}
    username: root
    password: 15102017
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_PORT}:8000/eureka

port:
  config: ${CONFIG_PORT}
  eureka: ${EUREKA_PORT}
  gateway: ${GATEWAY_PORT}
  auth: 0
  user: 0
  partner: 0
  chemical: 0
  chemical-tag: 0
  chemical-price: 0
  recipe: 0
  material: 0
  color: 0
  procedure: 0
  product: 0
